file_format: "npy_series"
image_size: ${input_size}
transforms:
  train:
    - EnsureChannelFirstd:
        keys: ["Image", "Mask"]
        channel_dim: "no_channel"
transforms_config:
  input_size: ${input_size}
  p_flip: [0.5, 0.5, 0.5]
  p_rotate: 0.5
  rotation_range: [0.175, 0.175, 0.175]
  p_zoom: 0.5
  min_zoom: 0.9
  max_zoom: 1.3
  use_percentiles_intensity_scaling: False
  lower: 0
  upper: 98
  p_elastic: 0.3
  elastic_sigma: [10, 20]
  elastic_mag: [100, 500]
